Repository markuspoerschke/iCal, pull requests merged in 2022-12, with the labels that each got.

#468 Update component-event.md
  website/docs/component-event.md
Labels: documentation

#452 Return self from Calendar.setPublishedTTL().
  CHANGELOG.md
  src/Domain/Entity/Calendar.php
Labels: enhancement

#476 Update phpmd/phpmd to 2.13
  .github/workflows/ci.yml
  composer.json
  composer.lock
Labels: dependencies

#477 Fix ackee tracker
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: documentation

#479 Fix email address
  CHANGELOG.md
  src/Domain/ValueObject/EmailAddress.php
  tests/Unit/Domain/ValueObject/EmailAddressTest.php
  tests/Unit/Presentation/Factory/EventFactoryTest.php
Labels: bug
